### ISSUE TITLE
Creating postgreSQL database in pgAdmin 4

### ISSUE THREAD

**Issue by vossca** [KobusMarais/Gladius-Navigation#10]
Does anyone know of better tools, I might be a little out of my depth.

**Comment by aeTherZA** [comment]
Are you installing PostgreSQL locally on your machine? Or is it hosted?

**Comment by vossca** [comment]
I installed it locally, I made two tables (one for frequently used routes and another for specific users' preferences) but I'm not sure how to export them so the structure will remain intact
